[package]
name = "z3rro"
version = "0.1.0"
edition = "2021"

[dependencies]
z3 = "^0.12"
ref-cast = "1.0"
num = "0.4"
once_cell = "1.8"
cfg-if = "1.0"
tracing = "0.1"
tempfile = "3.3"
thiserror = "1.0"

[features]
datatype-eureal = []
datatype-eureal-funcs = ["datatype-eureal"]
